/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>



void delay();
void gpio_init();
uint32_t* AHB1ENR=(uint32_t)0x40023830;//Declaring AHB1 register through RCC
uint32_t* GPIOA_MODER=(uint32_t)0x40020000;//Declaring GPIOA moder register
uint32_t* GPIOA_ODR=(uint32_t)0x40020014 ;//Declaring GPIOA ODR register


int main(void)
{
	gpio_init();
   while(1){
	   *GPIOA_ODR |=(1<<5);
	   delay();
	   *GPIOA_ODR &= ~(1<<5); // Turn LED off (clear PA5)
	   delay();

   }

}
void gpio_init(){
	*AHB1ENR |=(1<<0);
	*GPIOA_MODER &=~(1<<11);
	*GPIOA_MODER |= (1<<10);

}
void delay()
{
    int count;

    for(count = 0; count < 500000; count++) {
        // This empty loop will create a delay, you might need to adjust this
    }
}
